import { useLiveQuery } from 'dexie-react-hooks';
import { db } from '@/db/db';

export const useProducts = () => useLiveQuery(() => db.products.toArray(), [], [] as any[]);
export const useCustomers = () => useLiveQuery(() => db.customers.toArray(), [], [] as any[]);
export const useSales = () => useLiveQuery(() => db.sales.orderBy('ts').reverse().toArray(), [], [] as any[]);
export const useVendors = () => useLiveQuery(() => db.vendors.toArray(), [], [] as any[]);
export const usePOs = () => useLiveQuery(() => db.purchaseOrders.orderBy('createdAt').reverse().toArray(), [], [] as any[]);
export const useExpenses = () => useLiveQuery(() => db.expenses.orderBy('ts').reverse().toArray(), [], [] as any[]);
export const useHolds = () => useLiveQuery(() => db.holds.orderBy('ts').reverse().toArray(), [], [] as any[]);
export const useCoupons = () => useLiveQuery(() => db.coupons.toArray(), [], [] as any[]);
export const useStaff = () => useLiveQuery(() => db.staff.toArray(), [], [] as any[]);
export const useShifts = () => useLiveQuery(() => db.shifts.orderBy('openedAt').reverse().toArray(), [], [] as any[]);
export const useActivity = () => useLiveQuery(() => db.activity.orderBy('ts').reverse().limit(200).toArray(), [], [] as any[]);
export const useStockLogs = () => useLiveQuery(() => db.stockLogs.orderBy('ts').reverse().limit(400).toArray(), [], [] as any[]);
export const useTables = () => useLiveQuery(() => db.restaurantTables.toArray(), [], [] as any[]);
export const useLedger = () => useLiveQuery(() => db.ledger.orderBy('ts').reverse().limit(500).toArray(), [], [] as any[]);
export const useOrders = () => useLiveQuery(() => db.orders.orderBy('ts').reverse().limit(300).toArray(), [], [] as any[]);
export const useAttendance = () => useLiveQuery(() => db.attendance.toArray(), [], [] as any[]);
export const usePayroll = () => useLiveQuery(() => db.payroll.toArray(), [], [] as any[]);
export const useRecipes = () => useLiveQuery(() => db.recipes.toArray(), [], [] as any[]);
export const useSubscriptions = () => useLiveQuery(() => db.subscriptions.toArray(), [], [] as any[]);
export const useQuotes = () => useLiveQuery(() => db.quotes.orderBy('ts').reverse().toArray(), [], [] as any[]);
