import {
  LayoutDashboard, ShoppingCart, Package, Users, ReceiptText, Truck,
  Wallet, BarChart3, Ticket, UserCog, Settings, Boxes, Clock, HelpCircle, Utensils, Tag,
  Undo2, FileText, CalendarCheck, ClipboardList, MessageCircle,
  BookUser, ChefHat, CalendarClock, CookingPot, Repeat, Sparkles,
  Store, Wrench, CalendarDays, FileSpreadsheet, Stethoscope,
  ListChecks, Star, FlaskConical, Megaphone, Gift, IndianRupee, PackageX, Target, CheckSquare, Monitor, BookOpen, Wand2,
} from 'lucide-react';

export interface NavItem { path: string; label: string; icon: any; group: string; hint?: string }

export const NAV: NavItem[] = [
  { path: '/', label: 'Dashboard', icon: LayoutDashboard, group: 'Main', hint: 'KPIs & live overview' },
  { path: '/pos', label: 'Billing', icon: ShoppingCart, group: 'Main', hint: 'Point of sale terminal' },
  { path: '/inventory', label: 'Inventory', icon: Package, group: 'Main', hint: 'Products & stock' },
  { path: '/sales', label: 'Sales', icon: ReceiptText, group: 'Main', hint: 'Invoice history' },
  { path: '/returns', label: 'Returns', icon: Undo2, group: 'Main', hint: 'Refunds & exchange' },
  { path: '/orders', label: 'Orders', icon: ChefHat, group: 'Main', hint: 'Delivery & kitchen display' },
  { path: '/insights', label: 'Insights', icon: Sparkles, group: 'Main', hint: 'What to fix next' },
  { path: '/customers', label: 'Customers', icon: Users, group: 'Relations', hint: 'CRM & loyalty' },
  { path: '/vendors', label: 'Vendors', icon: Boxes, group: 'Relations', hint: 'Suppliers & payables' },
  { path: '/purchases', label: 'Purchases', icon: Truck, group: 'Relations', hint: 'Purchase orders' },
  { path: '/ledger', label: 'Khata', icon: BookUser, group: 'Money', hint: 'Dues, payables & statements' },
  { path: '/subscriptions', label: 'Subscriptions', icon: Repeat, group: 'Money', hint: 'Repeat & recurring orders' },
  { path: '/expenses', label: 'Expenses', icon: Wallet, group: 'Money', hint: 'Costs & cash out' },
  { path: '/tax', label: 'Tax Centre', icon: FileSpreadsheet, group: 'Money', hint: 'GSTR-1, HSN & filings' },
  { path: '/reports', label: 'Reports', icon: BarChart3, group: 'Money', hint: 'Analytics & GST' },
  { path: '/quotes', label: 'Quotes', icon: FileText, group: 'Money', hint: 'Estimates & proforma' },
  { path: '/dayclose', label: 'Day Close', icon: CalendarCheck, group: 'Money', hint: 'Z-report & cash count' },
  { path: '/offers', label: 'Offers', icon: Ticket, group: 'Money', hint: 'Coupons & loyalty' },
  { path: '/feedback', label: 'Feedback', icon: Star, group: 'Relations', hint: 'Ratings, NPS & complaints' },
  { path: '/campaigns', label: 'Campaigns', icon: Megaphone, group: 'Relations', hint: 'WhatsApp marketing & segments' },
  { path: '/loyalty', label: 'Gift & Wallet', icon: Gift, group: 'Money', hint: 'Gift cards, wallets & vouchers' },
  { path: '/pricing', label: 'Price Lists', icon: IndianRupee, group: 'Money', hint: 'Rate cards & customer pricing' },
  { path: '/simulator', label: 'What-if Lab', icon: FlaskConical, group: 'Money', hint: 'Pricing, margin & breakeven simulator' },
  { path: '/targets', label: 'Targets', icon: Target, group: 'Money', hint: 'Monthly & staff goals' },
  { path: '/autopo', label: 'Auto Reorder', icon: Wand2, group: 'Relations', hint: 'Smart purchase suggestions' },
  { path: '/menu', label: 'Digital Menu', icon: BookOpen, group: 'Ops', hint: 'QR menu & price card' },
  { path: '/display', label: 'Customer Screen', icon: Monitor, group: 'Ops', hint: 'Second display for customers' },
  { path: '/writeoff', label: 'Write-off', icon: PackageX, group: 'Ops', hint: 'Damage, expiry & wastage' },
  { path: '/tasks', label: 'Tasks', icon: CheckSquare, group: 'Ops', hint: 'To-do & reminders' },
  { path: '/labels', label: 'Labels', icon: Tag, group: 'Ops', hint: 'Barcode & price tags' },
  { path: '/stocktake', label: 'Stock Take', icon: ClipboardList, group: 'Ops', hint: 'Physical count & audit' },
  { path: '/reminders', label: 'Reminders', icon: MessageCircle, group: 'Ops', hint: 'Bulk WhatsApp dues' },
  { path: '/tables', label: 'Tables', icon: Utensils, group: 'Ops', hint: 'Restaurant floor' },
  { path: '/service', label: 'Service Jobs', icon: Wrench, group: 'Ops', hint: 'Repairs & job cards' },
  { path: '/appointments', label: 'Appointments', icon: CalendarDays, group: 'Ops', hint: 'Slot bookings' },
  { path: '/branches', label: 'Branches', icon: Store, group: 'Ops', hint: 'Outlets & stock transfer' },
  { path: '/recipes', label: 'Recipes', icon: CookingPot, group: 'Ops', hint: 'BOM, combos & production' },
  { path: '/attendance', label: 'Attendance', icon: CalendarClock, group: 'Ops', hint: 'Punch in/out & payroll' },
  { path: '/staff', label: 'Staff', icon: UserCog, group: 'Ops', hint: 'Users, shifts & PINs' },
  { path: '/activity', label: 'Activity', icon: Clock, group: 'Ops', hint: 'Audit log' },
  { path: '/cleanup', label: 'Data Doctor', icon: Stethoscope, group: 'System', hint: 'Find & fix catalogue issues' },
  { path: '/settings', label: 'Settings', icon: Settings, group: 'System', hint: 'Store & preferences' },
  { path: '/features', label: 'Feature Index', icon: ListChecks, group: 'System', hint: 'All 713 features, searchable' },
  { path: '/help', label: 'Help', icon: HelpCircle, group: 'System', hint: 'Shortcuts & guide' },
];

export const BOTTOM_NAV = ['/', '/pos', '/inventory', '/customers', '/reports'];
